UseIPv6: false
EthernetChannel: 60 #Mbit/s

TopLowerBets: 5
TopBets: 1.5
WordRequest: 2
LinkGift: 5
ActiveGift: 20
PercentForRandomLetter: 0.3

CasinoWinRatio: 8

CrocodileBetCoo: 2
CrocodileDefaultMaxBet: 5
CrocodileDefaultMinBet: 1

# Статистика
MaxStatPlayers: 10

# Типы государств
Type0Players: 1
Type1Players: 5
Type2Players: 10

# Время ожидания в секундах
MineWait: 14400

# Ограничение описания
DescriptionsMaxLen: 300

# Дней, после которых гос-ва удаляются
DaysToStatesRemove: 7

# Цены
PriceForChangeNick: 25
PriceForCasino: 5
PriceForCities: 5
PriceForNewState: 25
PriceForChangeStateNick: 40

# Максимум вывода в день
WithdrawDailyLimit: 64

# Рефералы
RefGift: 50

# Автоудаление сообщений в мини-игре Города
CitiesAutodelete: 10

# Ставка на города
CitiesBet: 5

# Время, которое нужно ждать до удаления игрока
CitiesTimeout: 50

Mining:
  Timeout: 500
  InitialGems: 5
  DefaultGems: 3
  BaseDeathChance: 0.01
  MaxDeathChance: 0.95
  IncDeathChance: 0.05
  BoostChance: 0.01
  BoostGemsMax: 50
  BoostGemsMin: 10

Advancements:
  Votes: 50

HintGift: 3

Flood:
  Casino: 10
  Pic: 10

Crocodile:
  MaxBet: 5
  MinBet: 1

ShopThemeWeights:
  armorer: 9
  blacksmith: 9
  desert: 3
  end: 7
  flower: 1
  heads: 7
  mine: 9
  music: 2
  nether: 5
  raiders: 10
  redstone: 5
  remains: 5
  sculk: 2
  water: 6
  witch: 8
  potions: 5
  books: 5
  decorations: 2