EthernetChannel: 60 #Mbit/s

TopLowerBets: 5
TopBets: 1.5
WordRequest: 2
IPSleepTime: 3600
LinkGift: 5
ActiveGift: 15
PercentForRandomLetter: 0.3

CasinoSleepTime: 150
CasinoWinRatio: 8

CrocodileBetCoo: 2
CrocodileDefaultMaxBet: 5
CrocodileDefaultMinBet: 1

# Статистика
MaxStatPlayers: 10

# Типы государств
Type0Players: 1
Type1Players: 3
Type2Players: 6

# Время ожидания в секундах
MineWait: 14400

# Ограничение описания
DescriptionsMaxLen: 300

# Дней, после которых гос-ва удаляются
DaysToStatesRemove: 7

# Шанс быть убитым в шахте | найти залежи
ChanceToDie: 0.011
ChanceToBoost: 0.009

# Количество изумрудов
MineMaxGems: 10
MineMaxBoost: 50

# Цены
PriceForChangeNick: 5
PriceForCasino: 5
PriceForCities: 5
PriceForNewState: 25
PriceForChangeStateNick: 40

# Максимум вывода в день
WithdrawDailyLimit: 64

# Рефералы
RefGift: 25

# Автоудаление сообщений в мини-игре Города
CitiesAutodelete: 10

# Ставка на города
CitiesBet: 5

# Время, которое нужно ждать до удаления игрока
CitiesTimeout: 50

AI:
  MaxTokens: 1500
  ContentSim: 0.7
  Try: 3
  FloodSleepTime: 10